version: '3.7'

services:
  server:
    build:
      context: ./app
      dockerfile: docker/server.Dockerfile
    environment:
      HOST: 0.0.0.0
      PORT: 5000 
      CLIENT_SCHEME: https
      CLIENT_HOST: client.proxy
      CLIENT_PORT: 443
  client:
    build:
      context: ./app
      dockerfile: docker/client.Dockerfile
      args:
        SERVER_SCHEME: https
        SERVER_HOST: server.proxy
        SERVER_PORT: 443
  proxy:
    build: ./proxy
    ports:
      - "443:443"
    networks: 
      default:
        aliases:
          - client.proxy
          - server.proxy
  chrome:
    build: ./chrome
    ports:
      - "3000:3000"
  test-integrations:
    build:
      context: ./app
      dockerfile: docker/tester.Dockerfile
    environment:
      CLIENT_SCHEME: https
      CLIENT_HOST: client.proxy
      CLIENT_PORT: 443
      CHROME_SCHEME: http
      CHROME_HOST: chrome
      CHROME_PORT: 3000
    depends_on:
      - proxy
      - chrome
